import sys
filepath = r'F:\Android\App\MiRoot2.1\app\src\main\java\com\wmqc\miroot\car\ble\DigitalCarKeyService.kt'

def w(s):
    return s + '\n'

with open(filepath, 'a', encoding='utf-8') as f:
    # Scan callback
    f.write(w('    // ============ BLE Scan Callback ============'))
    f.write(w(''))
    f.write(w('    private val scanCallback = object : ScanCallback() {'))
    f.write(w('        override fun onScanResult(callbackType: Int, result: ScanResult) {'))
    f.write(w('            if (!running) return'))
    f.write(w('            lastDataMs = System.currentTimeMillis()'))
    f.write(w('            val device = result.device'))
    f.write(w('            val rssi = result.rssi'))
    f.write(w('            val scanRecord = result.scanRecord?.bytes'))
    f.write(w('            LogHelper.d(TAG, "Found: " + device.address + " RSSI=" + rssi)'))
    f.write(w('            onDeviceFound?.invoke(device, rssi, scanRecord)'))
    f.write(w('            if (gatt == null) {'))
    f.write(w('                cancelScanTimeout()'))
    f.write(w('                connectDevice(device)'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        override fun onBatchScanResults(results: MutableList<ScanResult>) {'))
    f.write(w('            results.forEach { onScanResult(0, it) }'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        override fun onScanFailed(errorCode: Int) {'))
    f.write(w('            LogHelper.w(TAG, "Scan failed code=" + errorCode)'))
    f.write(w('            if (running) {'))
    f.write(w('                emitError(DigitalCarKeyError.SCAN_FAILED, "Scan error " + errorCode)'))
    f.write(w('                mainHandler.postDelayed({ restartScanIfNeeded() }, 1500L)'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w('    }'))
    f.write(w(''))
    
    # GATT callback
    f.write(w('    // ============ GATT Callback ============'))
    f.write(w(''))
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private val gattCallback = object : BluetoothGattCallback() {'))
    f.write(w(''))
    f.write(w('        override fun onConnectionStateChange(gatt: BluetoothGatt, status: Int, newState: Int) {'))
    f.write(w('            if (!running && newState != BluetoothProfile.STATE_DISCONNECTED) {'))
    f.write(w('                gatt.close()'))
    f.write(w('                return'))
    f.write(w('            }'))
    f.write(w('            when (newState) {'))
    f.write(w('                BluetoothProfile.STATE_CONNECTED -> {'))
    f.write(w('                    LogHelper.d(TAG, "GATT connected: " + gatt.device.address)'))
    f.write(w('                    cancelConnectTimeout()'))
    f.write(w('                    connectedAddress.set(gatt.device.address)'))
    f.write(w('                    emitState(DigitalCarKeyState.DISCOVERING_SERVICES)'))
    f.write(w('                    gatt.discoverServices()'))
    f.write(w('                }'))
    f.write(w('                BluetoothProfile.STATE_DISCONNECTED -> {'))
    f.write(w('                    val addr = gatt.device.address'))
    f.write(w('                    LogHelper.d(TAG, "GATT disconnected: " + addr + " status=" + status)'))
    f.write(w('                    if (connectedAddress.get() == addr) connectedAddress.set(null)'))
    f.write(w('                    gatt.close()'))
    f.write(w('                    if (this@DigitalCarKeyService.gatt == gatt) {'))
    f.write(w('                        this@DigitalCarKeyService.gatt = null'))
    f.write(w('                    }'))
    f.write(w('                    controlCharacteristic = null'))
    f.write(w('                    statusCharacteristic = null'))
    f.write(w('                    authCharacteristic = null'))
    f.write(w('                    isProcessingQueue = false'))
    f.write(w('                    pendingCommand.set(null)'))
    f.write(w('                    if (running) attemptReconnect()'))
    f.write(w('                    else emitState(DigitalCarKeyState.DISCONNECTED)'))
    f.write(w('                }'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        override fun onServicesDiscovered(gatt: BluetoothGatt, status: Int) {'))
    f.write(w('            if (status != BluetoothGatt.GATT_SUCCESS) {'))
    f.write(w('                LogHelper.w(TAG, "Service discovery failed: status=" + status)'))
    f.write(w('                emitError(DigitalCarKeyError.SERVICE_DISCOVERY_FAILED, "Discovery failed")'))
    f.write(w('                disconnectGatt()'))
    f.write(w('                attemptReconnect()'))
    f.write(w('                return'))
    f.write(w('            }'))
    f.write(w('            if (!running) return'))
    f.write(w('            val service = gatt.getService(DigitalCarKeyConstants.digitalKeyServiceUuid.uuid)'))
    f.write(w('            if (service == null) {'))
    f.write(w('                LogHelper.w(TAG, "DK service not found: " + DigitalCarKeyConstants.digitalKeyServiceUuid)'))
    f.write(w('                emitError(DigitalCarKeyError.SERVICE_NOT_FOUND, "DK service not found")'))
    f.write(w('                disconnectGatt()'))
    f.write(w('                attemptReconnect()'))
    f.write(w('                return'))
    f.write(w('            }'))
    f.write(w('            controlCharacteristic = service.getCharacteristic('))
    f.write(w('                DigitalCarKeyConstants.controlCharacteristicUuid.uuid)'))
    f.write(w('            statusCharacteristic = service.getCharacteristic('))
    f.write(w('                DigitalCarKeyConstants.statusNotificationUuid.uuid)'))
    f.write(w('            authCharacteristic = service.getCharacteristic('))
    f.write(w('                DigitalCarKeyConstants.authCharacteristicUuid.uuid)'))
    f.write(w('            if (controlCharacteristic == null) {'))
    f.write(w('                LogHelper.w(TAG, "Control char not found")'))
    f.write(w('                emitError(DigitalCarKeyError.CONTROL_CHAR_NOT_FOUND, "No control char")'))
    f.write(w('                return'))
    f.write(w('            }'))
    f.write(w('            if (statusCharacteristic != null) {'))
    f.write(w('                enableNotification(gatt, statusCharacteristic!!)'))
    f.write(w('            }'))
    f.write(w('            if (authCharacteristic != null) {'))
    f.write(w('                emitState(DigitalCarKeyState.AUTHENTICATING, "Authenticating...")'))
    f.write(w('                performAuthentication(gatt, authCharacteristic!!)'))
    f.write(w('            } else {'))
    f.write(w('                LogHelper.d(TAG, "No auth char, entering READY")'))
    f.write(w('                resetReconnectState()'))
    f.write(w('                emitState(DigitalCarKeyState.READY, "Ready")'))
    f.write(w('            }'))
    f.write(w('            cancelNoSignalCheck()'))
    f.write(w('            scheduleNoSignalCheck()'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        @Deprecated("Deprecated in Java")'))
    f.write(w('        override fun onCharacteristicChanged('))
    f.write(w('            gatt: BluetoothGatt,'))
    f.write(w('            characteristic: BluetoothGattCharacteristic,'))
    f.write(w('        ) { handleCharacteristicChanged(gatt, characteristic, characteristic.value) }'))
    f.write(w(''))
    f.write(w('        override fun onCharacteristicChanged('))
    f.write(w('            gatt: BluetoothGatt,'))
    f.write(w('            characteristic: BluetoothGattCharacteristic,'))
    f.write(w('            value: ByteArray,'))
    f.write(w('        ) { handleCharacteristicChanged(gatt, characteristic, value) }'))
    f.write(w(''))
    f.write(w('        override fun onCharacteristicWrite('))
    f.write(w('            gatt: BluetoothGatt,'))
    f.write(w('            characteristic: BluetoothGattCharacteristic,'))
    f.write(w('            status: Int,'))
    f.write(w('        ) {'))
    f.write(w('            val cmd = pendingCommand.get()'))
    f.write(w('            if (cmd != null && characteristic.uuid == cmd.characteristicUuid) {'))
    f.write(w('                val ok = status == BluetoothGatt.GATT_SUCCESS'))
    f.write(w('                if (ok) LogHelper.d(TAG, "Cmd " + cmd.id + " write success")'))
    f.write(w('                else LogHelper.w(TAG, "Cmd " + cmd.id + " write fail status=" + status)'))
    f.write(w('                completeCommand(cmd, ok, null)'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        override fun onCharacteristicRead('))
    f.write(w('            gatt: BluetoothGatt,'))
    f.write(w('            characteristic: BluetoothGattCharacteristic,'))
    f.write(w('            status: Int,'))
    f.write(w('        ) {'))
    f.write(w('            if (status == BluetoothGatt.GATT_SUCCESS) {'))
    f.write(w('                onCommandResult?.invoke('))
    f.write(w('                    BleCommand(id = -1, data = ByteArray(0), characteristicUuid = characteristic.uuid),'))
    f.write(w('                    true, characteristic.value)'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w(''))
    f.write(w('        override fun onDescriptorWrite('))
    f.write(w('            gatt: BluetoothGatt,'))
    f.write(w('            descriptor: BluetoothGattDescriptor,'))
    f.write(w('            status: Int,'))
    f.write(w('        ) { LogHelper.d(TAG, "Descriptor write " + descriptor.uuid + " status=" + status) }'))
    f.write(w('    }'))
    f.write(w(''))
    
    # Notification + Auth
    f.write(w('    // ============ Notification & Authentication ============'))
    f.write(w(''))
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun enableNotification(gatt: BluetoothGatt, characteristic: BluetoothGattCharacteristic) {'))
    f.write(w('        try {'))
    f.write(w('            gatt.setCharacteristicNotification(characteristic, true)'))
    f.write(w('            val descriptor = characteristic.getDescriptor('))
    f.write(w('                DigitalCarKeyConstants.clientConfigDescriptor.uuid)'))
    f.write(w('            if (descriptor != null) {'))
    f.write(w('                @Suppress("DEPRECATION")'))
    f.write(w('                descriptor.value = BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE'))
    f.write(w('                @Suppress("DEPRECATION")'))
    f.write(w('                gatt.writeDescriptor(descriptor)'))
    f.write(w('                LogHelper.d(TAG, "Notification enabled for " + characteristic.uuid)'))
    f.write(w('            }'))
    f.write(w('        } catch (e: Exception) {'))
    f.write(w('            LogHelper.w(TAG, "Enable notification failed: " + e.message)'))
    f.write(w('        }'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun performAuthentication(gatt: BluetoothGatt, characteristic: BluetoothGattCharacteristic) {'))
    f.write(w('        // TODO: Replace with actual DK authentication flow'))
    f.write(w('        LogHelper.d(TAG, "Auth placeholder: marking as ready")'))
    f.write(w('        resetReconnectState()'))
    f.write(w('        emitState(DigitalCarKeyState.READY, "Auth complete")'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun handleCharacteristicChanged('))
    f.write(w('        gatt: BluetoothGatt,'))
    f.write(w('        characteristic: BluetoothGattCharacteristic,'))
    f.write(w('        value: ByteArray,'))
    f.write(w('    ) {'))
    f.write(w('        lastDataMs = System.currentTimeMillis()'))
    f.write(w('        scheduleNoSignalCheck()'))
    f.write(w('        val uuid = characteristic.uuid'))
    f.write(w('        LogHelper.d(TAG, "Notification: " + uuid + " size=" + value.size)'))
    f.write(w('        val cmd = pendingCommand.get()'))
    f.write(w('        if (cmd != null && uuid == cmd.characteristicUuid) {'))
    f.write(w('            completeCommand(cmd, true, value)'))
    f.write(w('        }'))
    f.write(w('        onCommandResult?.invoke('))
    f.write(w('            BleCommand(id = -2, data = ByteArray(0), characteristicUuid = uuid),'))
    f.write(w('            true, value)'))
    f.write(w('    }'))
    f.write(w(''))
    
    # Companion
    f.write(w('    private companion object {'))
    f.write(w('        private const val TAG = "DigitalCarKeyService"'))
    f.write(w('    }'))
    f.write(w('}'))

print('Part 4 written (callbacks + notification + companion)')
