import sys
filepath = r'F:\Android\App\MiRoot2.1\app\src\main\java\com\wmqc\miroot\car\ble\DigitalCarKeyService.kt'

def w(s):
    return s + '\n'

with open(filepath, 'a', encoding='utf-8') as f:
    # connectToDevice
    f.write(w('    fun connectToDevice(device: BluetoothDevice) {'))
    f.write(w('        if (!checkPreconditions()) return'))
    f.write(w('        stopScanInternal()'))
    f.write(w('        cancelScanTimeout()'))
    f.write(w('        running = true'))
    f.write(w('        connectDevice(device)'))
    f.write(w('    }'))
    f.write(w(''))
    
    # sendCommand
    f.write(w('    fun sendCommand('))
    f.write(w('        data: ByteArray,'))
    f.write(w('        characteristicUuid: UUID = DigitalCarKeyConstants.controlCharacteristicUuid.uuid,'))
    f.write(w('        writeType: Int = BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE,'))
    f.write(w('        timeoutMs: Long = DigitalCarKeyConstants.COMMAND_TIMEOUT_MS,'))
    f.write(w('        onResult: ((Boolean, ByteArray?) -> Unit)? = null,'))
    f.write(w('    ): Int {'))
    f.write(w('        val id = commandSequence.incrementAndGet()'))
    f.write(w('        val cmd = BleCommand('))
    f.write(w('            id = id,'))
    f.write(w('            data = data,'))
    f.write(w('            characteristicUuid = characteristicUuid,'))
    f.write(w('            writeType = writeType,'))
    f.write(w('            timeoutMs = timeoutMs,'))
    f.write(w('            onResult = onResult,'))
    f.write(w('        )'))
    f.write(w('        commandQueue.add(cmd)'))
    f.write(w('        LogHelper.d(TAG, "Cmd " + id + " queued, size=" + commandQueue.size)'))
    f.write(w('        processCommandQueue()'))
    f.write(w('        return id'))
    f.write(w('    }'))
    f.write(w(''))
    
    # disconnect
    f.write(w('    fun disconnect() {'))
    f.write(w('        autoReconnect = false'))
    f.write(w('        disconnectGatt()'))
    f.write(w('        commandQueue.clear()'))
    f.write(w('        pendingCommand.set(null)'))
    f.write(w('        emitState(DigitalCarKeyState.DISCONNECTED)'))
    f.write(w('    }'))
    f.write(w(''))
    
    # checkPreconditions
    f.write(w('    // ============ Internal Helpers ============'))
    f.write(w(''))
    f.write(w('    private fun checkPreconditions(): Boolean {'))
    f.write(w('        if (!DigitalCarKeyPermissionHelper.isLeSupported(app)) {'))
    f.write(w('            emitError(DigitalCarKeyError.INTERNAL_ERROR, "No BLE support")'))
    f.write(w('            return false'))
    f.write(w('        }'))
    f.write(w('        if (!DigitalCarKeyPermissionHelper.hasAll(app)) {'))
    f.write(w('            emitError(DigitalCarKeyError.PERMISSION_DENIED, "Missing BLE permissions")'))
    f.write(w('            return false'))
    f.write(w('        }'))
    f.write(w('        if (!isBluetoothEnabled()) {'))
    f.write(w('            emitError(DigitalCarKeyError.BLUETOOTH_OFF, "Bluetooth is off")'))
    f.write(w('            return false'))
    f.write(w('        }'))
    f.write(w('        return true'))
    f.write(w('    }'))
    f.write(w(''))
    
    # Scan internal
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun startScanInternal(filters: List<ScanFilter>) {'))
    f.write(w('        val leScanner = scanner ?: return'))
    f.write(w('        val settings = ScanSettings.Builder()'))
    f.write(w('            .setScanMode(DigitalCarKeyConstants.DEFAULT_SCAN_MODE)'))
    f.write(w('            .build()'))
    f.write(w('        try {'))
    f.write(w('            leScanner.startScan(filters, settings, scanCallback)'))
    f.write(w('            LogHelper.d(TAG, "Scan started")'))
    f.write(w('        } catch (e: Exception) {'))
    f.write(w('            LogHelper.w(TAG, "Scan start failed: " + e.message)'))
    f.write(w('            emitError(DigitalCarKeyError.SCAN_FAILED, e.message ?: "")'))
    f.write(w('        }'))
    f.write(w('    }'))
    f.write(w(''))
    
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun stopScanInternal() {'))
    f.write(w('        try { scanner?.stopScan(scanCallback) }'))
    f.write(w('        catch (e: Exception) { LogHelper.w(TAG, "Scan stop: " + e.message) }'))
    f.write(w('    }'))
    f.write(w(''))
    
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun restartScanIfNeeded() {'))
    f.write(w('        if (!running || gatt != null) return'))
    f.write(w('        stopScanInternal()'))
    f.write(w('        startScanInternal(createVehicleFilter())'))
    f.write(w('    }'))
    f.write(w(''))
    
    f.write(w('    private fun createVehicleFilter(): List<ScanFilter> {'))
    f.write(w('        return listOf('))
    f.write(w('            ScanFilter.Builder()'))
    f.write(w('                .setServiceUuid(DigitalCarKeyConstants.digitalKeyServiceUuid)'))
    f.write(w('                .build()'))
    f.write(w('        )'))
    f.write(w('    }'))
    f.write(w(''))
    
    # connectDevice
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun connectDevice(device: BluetoothDevice) {'))
    f.write(w('        cancelConnectTimeout()'))
    f.write(w('        disconnectGatt()'))
    f.write(w('        emitState(DigitalCarKeyState.CONNECTING, "Connecting: " + device.address)'))
    f.write(w('        LogHelper.d(TAG, "Connecting to " + device.address)'))
    f.write(w('        gatt = device.connectGatt('))
    f.write(w('            app,'))
    f.write(w('            false,'))
    f.write(w('            gattCallback,'))
    f.write(w('            BluetoothDevice.TRANSPORT_LE,'))
    f.write(w('        )'))
    f.write(w('        scheduleConnectTimeout(device.address)'))
    f.write(w('    }'))
    f.write(w(''))
    
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun disconnectGatt() {'))
    f.write(w('        try { gatt?.disconnect(); gatt?.close() }'))
    f.write(w('        catch (e: Exception) { LogHelper.w(TAG, "Gatt close: " + e.message) }'))
    f.write(w('        gatt = null'))
    f.write(w('        connectedAddress.set(null)'))
    f.write(w('        controlCharacteristic = null'))
    f.write(w('        statusCharacteristic = null'))
    f.write(w('        authCharacteristic = null'))
    f.write(w('    }'))
    f.write(w(''))
    
    # Command Queue
    f.write(w('    // ============ Command Queue ============'))
    f.write(w(''))
    f.write(w('    @SuppressLint("MissingPermission")'))
    f.write(w('    private fun processCommandQueue() {'))
    f.write(w('        if (isProcessingQueue || gatt == null) return'))
    f.write(w('        val gatt = gatt ?: return'))
    f.write(w('        val cmd = commandQueue.poll() ?: return'))
    f.write(w('        isProcessingQueue = true'))
    f.write(w('        pendingCommand.set(cmd)'))
    f.write(w('        val characteristic = gatt.getService(DigitalCarKeyConstants.digitalKeyServiceUuid.uuid)'))
    f.write(w('            ?.getCharacteristic(cmd.characteristicUuid)'))
    f.write(w('        if (characteristic == null) {'))
    f.write(w('            LogHelper.e(TAG, "Cmd " + cmd.id + ": char not found " + cmd.characteristicUuid)'))
    f.write(w('            completeCommand(cmd, false, null)'))
    f.write(w('            return'))
    f.write(w('        }'))
    f.write(w('        characteristic.writeType = cmd.writeType'))
    f.write(w('        characteristic.value = cmd.data'))
    f.write(w('        val success = try { gatt.writeCharacteristic(characteristic) }'))
    f.write(w('            catch (e: Exception) { LogHelper.e(TAG, "Cmd " + cmd.id + " write: " + e.message); false }'))
    f.write(w('        if (!success) {'))
    f.write(w('            LogHelper.w(TAG, "Cmd " + cmd.id + " write failed")'))
    f.write(w('            completeCommand(cmd, false, null)'))
    f.write(w('        } else {'))
    f.write(w('            LogHelper.d(TAG, "Cmd " + cmd.id + " written")'))
    f.write(w('            if (cmd.writeType == BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE) {'))
    f.write(w('                completeCommand(cmd, true, null)'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w('    }'))
    f.write(w(''))
    
    f.write(w('    private fun completeCommand(cmd: BleCommand, success: Boolean, response: ByteArray?) {'))
    f.write(w('        cmd.onResult?.invoke(success, response)'))
    f.write(w('        onCommandResult?.invoke(cmd, success, response)'))
    f.write(w('        pendingCommand.compareAndSet(cmd, null)'))
    f.write(w('        isProcessingQueue = false'))
    f.write(w('        processCommandQueue()'))
    f.write(w('    }'))
    f.write(w(''))

print('Part 2 written (internal helpers)')
