import sys
filepath = r'F:\Android\App\MiRoot2.1\app\src\main\java\com\wmqc\miroot\car\ble\DigitalCarKeyService.kt'

def w(s):
    return s + '\n'

with open(filepath, 'a', encoding='utf-8') as f:
    # Timeout Management
    f.write(w('    // ============ Timeout Management ============'))
    f.write(w(''))
    f.write(w('    private fun scheduleScanTimeout() {'))
    f.write(w('        cancelScanTimeout()'))
    f.write(w('        val task = Runnable {'))
    f.write(w('            if (!running) return@Runnable'))
    f.write(w('            if (gatt == null) {'))
    f.write(w('                LogHelper.w(TAG, "Scan timeout")'))
    f.write(w('                emitError(DigitalCarKeyError.SCAN_TIMEOUT, "No vehicle found")'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w('        scanTimeoutTask = task'))
    f.write(w('        mainHandler.postDelayed(task, DigitalCarKeyConstants.SCAN_TIMEOUT_MS)'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun cancelScanTimeout() {'))
    f.write(w('        scanTimeoutTask?.let { mainHandler.removeCallbacks(it) }'))
    f.write(w('        scanTimeoutTask = null'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun scheduleConnectTimeout(deviceAddress: String) {'))
    f.write(w('        cancelConnectTimeout()'))
    f.write(w('        val task = Runnable {'))
    f.write(w('            if (connectedAddress.get() == deviceAddress) {'))
    f.write(w('                LogHelper.w(TAG, "Connect timeout: " + deviceAddress)'))
    f.write(w('                emitError(DigitalCarKeyError.CONNECT_TIMEOUT, "Connect timeout")'))
    f.write(w('                disconnectGatt()'))
    f.write(w('                attemptReconnect()'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w('        connectTimeoutTask = task'))
    f.write(w('        mainHandler.postDelayed(task, DigitalCarKeyConstants.CONNECT_TIMEOUT_MS)'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun cancelConnectTimeout() {'))
    f.write(w('        connectTimeoutTask?.let { mainHandler.removeCallbacks(it) }'))
    f.write(w('        connectTimeoutTask = null'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun scheduleNoSignalCheck() {'))
    f.write(w('        cancelNoSignalCheck()'))
    f.write(w('        val task = Runnable {'))
    f.write(w('            if (!running) return@Runnable'))
    f.write(w('            val elapsed = System.currentTimeMillis() - lastDataMs'))
    f.write(w('            if (elapsed > DigitalCarKeyConstants.NO_SIGNAL_TIMEOUT_MS && gatt != null) {'))
    f.write(w('                LogHelper.w(TAG, "No signal for " + elapsed + "ms")'))
    f.write(w('                emitState(DigitalCarKeyState.RECONNECTING, "No signal")'))
    f.write(w('                disconnectGatt()'))
    f.write(w('                attemptReconnect()'))
    f.write(w('            }'))
    f.write(w('        }'))
    f.write(w('        noSignalTask = task'))
    f.write(w('        mainHandler.postDelayed(task, DigitalCarKeyConstants.NO_SIGNAL_TIMEOUT_MS)'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun cancelNoSignalCheck() {'))
    f.write(w('        noSignalTask?.let { mainHandler.removeCallbacks(it) }'))
    f.write(w('        noSignalTask = null'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun cancelAllTimeouts() {'))
    f.write(w('        cancelScanTimeout()'))
    f.write(w('        cancelConnectTimeout()'))
    f.write(w('        cancelNoSignalCheck()'))
    f.write(w('    }'))
    f.write(w(''))
    
    # Reconnect
    f.write(w('    // ============ Reconnect ============'))
    f.write(w(''))
    f.write(w('    private fun attemptReconnect() {'))
    f.write(w('        if (!autoReconnect || !running) return'))
    f.write(w('        val attempts = reconnectAttempts.incrementAndGet()'))
    f.write(w('        if (attempts > DigitalCarKeyConstants.MAX_RECONNECT_ATTEMPTS) {'))
    f.write(w('            LogHelper.e(TAG, "Reconnect exhausted: " + attempts)'))
    f.write(w('            emitError(DigitalCarKeyError.CONNECT_FAILED, "Reconnect failed")'))
    f.write(w('            return'))
    f.write(w('        }'))
    f.write(w('        val delay = calculateBackoff(attempts)'))
    f.write(w('        LogHelper.d(TAG, "Reconnect " + attempts + " in " + delay + "ms")'))
    f.write(w('        emitState(DigitalCarKeyState.RECONNECTING, "Retry in " + delay + "ms")'))
    f.write(w('        mainScope.launch {'))
    f.write(w('            kotlinx.coroutines.delay(delay)'))
    f.write(w('            if (running && autoReconnect) startScan()'))
    f.write(w('        }'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun calculateBackoff(attempt: Int): Long {'))
    f.write(w('        val base = DigitalCarKeyConstants.RECONNECT_BASE_DELAY_MS'))
    f.write(w('        val exponential = base shl (attempt - 1).coerceAtMost(4)'))
    f.write(w('        return exponential.coerceAtMost(DigitalCarKeyConstants.RECONNECT_MAX_DELAY_MS)'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun resetReconnectState() { reconnectAttempts.set(0) }'))
    f.write(w(''))
    f.write(w('    private fun handleBluetoothOff() {'))
    f.write(w('        emitError(DigitalCarKeyError.BLUETOOTH_OFF, "Bluetooth off")'))
    f.write(w('        disconnectGatt()'))
    f.write(w('        commandQueue.clear()'))
    f.write(w('        pendingCommand.set(null)'))
    f.write(w('        isProcessingQueue = false'))
    f.write(w('    }'))
    f.write(w(''))
    
    # State Flow
    f.write(w('    // ============ State Flow ============'))
    f.write(w(''))
    f.write(w('    private fun emitState(state: DigitalCarKeyState, message: String = "") {'))
    f.write(w('        _state.value = DigitalCarKeyEvent(state = state, message = message)'))
    f.write(w('    }'))
    f.write(w(''))
    f.write(w('    private fun emitError(error: DigitalCarKeyError, message: String = "") {'))
    f.write(w('        _state.value = DigitalCarKeyEvent('))
    f.write(w('            state = when (error) {'))
    f.write(w('                DigitalCarKeyError.BLUETOOTH_OFF -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.PERMISSION_DENIED -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.SCAN_TIMEOUT -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.SCAN_FAILED -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.CONNECT_TIMEOUT -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.CONNECT_FAILED -> DigitalCarKeyState.FAILED'))
    f.write(w('                DigitalCarKeyError.NO_SIGNAL -> DigitalCarKeyState.RECONNECTING'))
    f.write(w('                else -> DigitalCarKeyState.FAILED'))
    f.write(w('            },'))
    f.write(w('            error = error,'))
    f.write(w('            message = message,'))
    f.write(w('        )'))
    f.write(w('    }'))
    f.write(w(''))

print('Part 3 written (timeout + reconnect + state flow)')
