import sys
filepath = r'F:\Android\App\MiRoot2.1\app\src\main\java\com\wmqc\miroot\car\ble\DigitalCarKeyService.kt'

def w(s):
    return s + '\n'

lines = []

lines.append(w('/*'))
lines.append(w(' * Author: AntiOblivionis'))
lines.append(w(' * QQ: 319641317'))
lines.append(w(' * Github: https://github.com/GoldenglowSusie/'))
lines.append(w(' * Bilibili: \u7f57\u5fb7\u5c9b0\u5e72\u5458\u6280\u5e08\u6f84\u95ea'))
lines.append(w(' *'))
lines.append(w(' * Co-developed with AI assistants:'))
lines.append(w(' * - Cursor'))
lines.append(w(' * - Claude-4.5-Sonnet'))
lines.append(w(' * - GPT-5'))
lines.append(w(' * - Gemini-2.5-Pro'))
lines.append(w(' */'))
lines.append(w(''))
lines.append(w('package com.wmqc.miroot.car.ble'))
lines.append(w(''))
lines.append(w('import android.annotation.SuppressLint'))
lines.append(w('import android.bluetooth.BluetoothAdapter'))
lines.append(w('import android.bluetooth.BluetoothDevice'))
lines.append(w('import android.bluetooth.BluetoothGatt'))
lines.append(w('import android.bluetooth.BluetoothGattCallback'))
lines.append(w('import android.bluetooth.BluetoothGattCharacteristic'))
lines.append(w('import android.bluetooth.BluetoothGattDescriptor'))
lines.append(w('import android.bluetooth.BluetoothManager'))
lines.append(w('import android.bluetooth.BluetoothProfile'))
lines.append(w('import android.bluetooth.le.BluetoothLeScanner'))
lines.append(w('import android.bluetooth.le.ScanCallback'))
lines.append(w('import android.bluetooth.le.ScanFilter'))
lines.append(w('import android.bluetooth.le.ScanResult'))
lines.append(w('import android.bluetooth.le.ScanSettings'))
lines.append(w('import android.content.BroadcastReceiver'))
lines.append(w('import android.content.Context'))
lines.append(w('import android.content.Intent'))
lines.append(w('import android.content.IntentFilter'))
lines.append(w('import android.os.Handler'))
lines.append(w('import android.os.Looper'))
lines.append(w('import com.wmqc.miroot.lyrics.LogHelper'))
lines.append(w('import kotlinx.coroutines.CoroutineScope'))
lines.append(w('import kotlinx.coroutines.Dispatchers'))
lines.append(w('import kotlinx.coroutines.SupervisorJob'))
lines.append(w('import kotlinx.coroutines.delay'))
lines.append(w('import kotlinx.coroutines.flow.MutableStateFlow'))
lines.append(w('import kotlinx.coroutines.flow.StateFlow'))
lines.append(w('import kotlinx.coroutines.flow.asStateFlow'))
lines.append(w('import kotlinx.coroutines.launch'))
lines.append(w('import java.util.UUID'))
lines.append(w('import java.util.concurrent.ConcurrentLinkedQueue'))
lines.append(w('import java.util.concurrent.atomic.AtomicInteger'))
lines.append(w('import java.util.concurrent.atomic.AtomicReference'))
lines.append(w(''))

# Enums
lines.append(w('enum class DigitalCarKeyState {'))
lines.append(w('    IDLE,'))
lines.append(w('    SCANNING,'))
lines.append(w('    CONNECTING,'))
lines.append(w('    DISCOVERING_SERVICES,'))
lines.append(w('    AUTHENTICATING,'))
lines.append(w('    READY,'))
lines.append(w('    RECONNECTING,'))
lines.append(w('    FAILED,'))
lines.append(w('    DISCONNECTED,'))
lines.append(w('}'))
lines.append(w(''))

lines.append(w('enum class DigitalCarKeyError {'))
lines.append(w('    BLUETOOTH_OFF,'))
lines.append(w('    PERMISSION_DENIED,'))
lines.append(w('    SCAN_TIMEOUT,'))
lines.append(w('    SCAN_FAILED,'))
lines.append(w('    CONNECT_TIMEOUT,'))
lines.append(w('    CONNECT_FAILED,'))
lines.append(w('    SERVICE_DISCOVERY_FAILED,'))
lines.append(w('    SERVICE_NOT_FOUND,'))
lines.append(w('    CONTROL_CHAR_NOT_FOUND,'))
lines.append(w('    STATUS_CHAR_NOT_FOUND,'))
lines.append(w('    AUTH_TIMEOUT,'))
lines.append(w('    AUTH_FAILED,'))
lines.append(w('    COMMAND_TIMEOUT,'))
lines.append(w('    COMMAND_FAILED,'))
lines.append(w('    INTERNAL_ERROR,'))
lines.append(w('    NO_SIGNAL,'))
lines.append(w('}'))
lines.append(w(''))

lines.append(w('data class DigitalCarKeyEvent('))
lines.append(w('    val state: DigitalCarKeyState,'))
lines.append(w('    val error: DigitalCarKeyError? = null,'))
lines.append(w('    val message: String = "",'))
lines.append(w('    val timestampMs: Long = System.currentTimeMillis(),'))
lines.append(w(')'))
lines.append(w(''))

lines.append(w('data class BleCommand('))
lines.append(w('    val id: Int,'))
lines.append(w('    val data: ByteArray,'))
lines.append(w('    val characteristicUuid: UUID,'))
lines.append(w('    val writeType: Int = BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE,'))
lines.append(w('    val timeoutMs: Long = DigitalCarKeyConstants.COMMAND_TIMEOUT_MS,'))
lines.append(w('    val onResult: ((Boolean, ByteArray?) -> Unit)? = null,'))
lines.append(w(')'))
lines.append(w(''))

# Now class DigitalCarKeyService
class_content = []
class_content.append(w('class DigitalCarKeyService(context: Context) {'))
class_content.append(w(''))
class_content.append(w('    private val app = context.applicationContext'))
class_content.append(w('    private val mainHandler = Handler(Looper.getMainLooper())'))
class_content.append(w('    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)'))
class_content.append(w('    private val mainScope = CoroutineScope(SupervisorJob() + Dispatchers.Main)'))
class_content.append(w(''))
class_content.append(w('    private val bluetoothManager ='))
class_content.append(w('        app.getSystemService(Context.BLUETOOTH_SERVICE) as? BluetoothManager'))
class_content.append(w('    private val adapter: BluetoothAdapter? = bluetoothManager?.adapter'))
class_content.append(w('    private val scanner: BluetoothLeScanner? get() = adapter?.bluetoothLeScanner'))
class_content.append(w(''))
class_content.append(w('    private var gatt: BluetoothGatt? = null'))
class_content.append(w('    private val connectedAddress = AtomicReference<String?>(null)'))
class_content.append(w('    private val reconnectAttempts = AtomicInteger(0)'))
class_content.append(w(''))
class_content.append(w('    private var controlCharacteristic: BluetoothGattCharacteristic? = null'))
class_content.append(w('    private var statusCharacteristic: BluetoothGattCharacteristic? = null'))
class_content.append(w('    private var authCharacteristic: BluetoothGattCharacteristic? = null'))
class_content.append(w(''))
class_content.append(w('    private val commandQueue = ConcurrentLinkedQueue<BleCommand>()'))
class_content.append(w('    private val pendingCommand = AtomicReference<BleCommand?>(null)'))
class_content.append(w('    private var commandSequence = AtomicInteger(0)'))
class_content.append(w('    private var isProcessingQueue = false'))
class_content.append(w(''))
class_content.append(w('    private val _state = MutableStateFlow(DigitalCarKeyEvent(DigitalCarKeyState.IDLE))'))
class_content.append(w('    val state: StateFlow<DigitalCarKeyEvent> = _state.asStateFlow()'))
class_content.append(w(''))
class_content.append(w('    var onDeviceFound: ((BluetoothDevice, Int, ByteArray?) -> Unit)? = null'))
class_content.append(w('    var onCommandResult: ((BleCommand, Boolean, ByteArray?) -> Unit)? = null'))
class_content.append(w(''))
class_content.append(w('    private var running = false'))
class_content.append(w('    private var connectTimeoutTask: Runnable? = null'))
class_content.append(w('    private var scanTimeoutTask: Runnable? = null'))
class_content.append(w('    private var noSignalTask: Runnable? = null'))
class_content.append(w('    private var lastDataMs = 0L'))
class_content.append(w('    private var autoReconnect = true'))
class_content.append(w(''))
class_content.append(w('    private val bluetoothStateReceiver = object : BroadcastReceiver() {'))
class_content.append(w('        override fun onReceive(context: Context, intent: Intent) {'))
class_content.append(w('            val action = intent.action'))
class_content.append(w('            if (BluetoothAdapter.ACTION_STATE_CHANGED == action) {'))
class_content.append(w('                val s = intent.getIntExtra(BluetoothAdapter.EXTRA_STATE, BluetoothAdapter.ERROR)'))
class_content.append(w('                when (s) {'))
class_content.append(w('                    BluetoothAdapter.STATE_TURNING_OFF, BluetoothAdapter.STATE_OFF -> {'))
class_content.append(w('                        LogHelper.w(TAG, "Bluetooth turned off")'))
class_content.append(w('                        handleBluetoothOff()'))
class_content.append(w('                    }'))
class_content.append(w('                    BluetoothAdapter.STATE_ON -> {'))
class_content.append(w('                        LogHelper.d(TAG, "Bluetooth turned on")'))
class_content.append(w('                        if (running) restartScanIfNeeded()'))
class_content.append(w('                    }'))
class_content.append(w('                }'))
class_content.append(w('            }'))
class_content.append(w('        }'))
class_content.append(w('    }'))
class_content.append(w(''))
class_content.append(w('    init {'))
class_content.append(w('        try {'))
class_content.append(w('            val filter = IntentFilter(BluetoothAdapter.ACTION_STATE_CHANGED)'))
class_content.append(w('            app.registerReceiver(bluetoothStateReceiver, filter)'))
class_content.append(w('        } catch (e: Exception) {'))
class_content.append(w('            LogHelper.w(TAG, "register BT receiver failed: " + e.message)'))
class_content.append(w('        }'))
class_content.append(w('    }'))
class_content.append(w(''))

# Public API section
class_content.append(w('    // ============ Public API ============'))
class_content.append(w(''))
class_content.append(w('    fun isBluetoothEnabled(): Boolean = adapter?.isEnabled == true'))
class_content.append(w(''))
class_content.append(w('    fun getConnectedDeviceAddress(): String? = connectedAddress.get()'))
class_content.append(w(''))
class_content.append(w('    fun setAutoReconnect(enable: Boolean) { autoReconnect = enable }'))
class_content.append(w(''))
class_content.append(w('    fun startScan() {'))
class_content.append(w('        if (!checkPreconditions()) return'))
class_content.append(w('        running = true'))
class_content.append(w('        emitState(DigitalCarKeyState.SCANNING)'))
class_content.append(w('        lastDataMs = System.currentTimeMillis()'))
class_content.append(w('        startScanInternal(createVehicleFilter())'))
class_content.append(w('        scheduleScanTimeout()'))
class_content.append(w('    }'))
class_content.append(w(''))
class_content.append(w('    fun startScanWithFilter(filter: ScanFilter) {'))
class_content.append(w('        if (!checkPreconditions()) return'))
class_content.append(w('        running = true'))
class_content.append(w('        emitState(DigitalCarKeyState.SCANNING)'))
class_content.append(w('        lastDataMs = System.currentTimeMillis()'))
class_content.append(w('        startScanInternal(listOf(filter))'))
class_content.append(w('        scheduleScanTimeout()'))
class_content.append(w('    }'))
class_content.append(w(''))
class_content.append(w('    fun stopScan() {'))
class_content.append(w('        cancelScanTimeout()'))
class_content.append(w('        stopScanInternal()'))
class_content.append(w('    }'))
class_content.append(w(''))
class_content.append(w('    fun shutdown() {'))
class_content.append(w('        running = false'))
class_content.append(w('        autoReconnect = false'))
class_content.append(w('        stopScanInternal()'))
class_content.append(w('        disconnectGatt()'))
class_content.append(w('        commandQueue.clear()'))
class_content.append(w('        pendingCommand.set(null)'))
class_content.append(w('        isProcessingQueue = false'))
class_content.append(w('        cancelAllTimeouts()'))
class_content.append(w('        emitState(DigitalCarKeyState.DISCONNECTED)'))
class_content.append(w('        try { app.unregisterReceiver(bluetoothStateReceiver) } catch (_: Exception) { }'))
class_content.append(w('    }'))
class_content.append(w(''))

with open(filepath, 'w', encoding='utf-8') as f:
    # Write header and imports
    for line in lines:
        f.write(line)
    # Write class content
    for line in class_content:
        f.write(line)

print(f'Part 1 written: {len(lines)} header lines + {len(class_content)} class lines')
